//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demkaaaa.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryPrice
    {
        public int IdGistoryPrice { get; set; }
        public Nullable<int> IdObject { get; set; }
        public string TypeObject { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
    }
}
