//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demkaaaa.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        public int IdOrder { get; set; }
        public int IdService { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> IdWorker { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Service Service { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
