//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demkaaaa.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WV_Order
    {
        public string Client { get; set; }
        public string NameService { get; set; }
        public string NameProduct { get; set; }
    }
}
